/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketmasterproject;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
//import static ticketmasterproject.BuyTicketGUI.totalPriceLabel;

/**
 *
 * @author Grigor Danut and Antonio Penna
 */

//open a GUI frame
public class CheckPriceGUI extends javax.swing.JFrame {
    
    //declare the object p of the class Person   
    Person p;   
    
    /**
     * Creates new form TicketGUI
     */
    public CheckPriceGUI() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        youthCheckBox = new javax.swing.JCheckBox();
        adultCheckBox = new javax.swing.JCheckBox();
        elderCheckBox = new javax.swing.JCheckBox();
        buyTicketButton = new javax.swing.JButton();
        checkPriceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalPriceButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numTicketsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Ticketmaster");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Check Your Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(497, 497, 497))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Please select the category");

        categoryComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Star", "Premium", "Economy" }));
        categoryComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryComboBoxMouseClicked(evt);
            }
        });
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Please select your age:");

        buttonGroup1.add(youthCheckBox);
        youthCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        youthCheckBox.setText("Youth");
        youthCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                youthCheckBoxMouseClicked(evt);
            }
        });

        buttonGroup1.add(adultCheckBox);
        adultCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adultCheckBox.setText("Adult");
        adultCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adultCheckBoxMouseClicked(evt);
            }
        });

        buttonGroup1.add(elderCheckBox);
        elderCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elderCheckBox.setText("Elder ");
        elderCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderCheckBoxMouseClicked(evt);
            }
        });

        buyTicketButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buyTicketButton.setText("Buy This Ticket");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        checkPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Your Price for This Ticket is €");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("  between 5 and 18 yaears old");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("  between 18 and 65 years old");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("  Over 65 years old");

        totalPriceButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalPriceButton.setText("Total Price");
        totalPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Your Total Price is €");

        totalCostLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Please Enter Number of Tickets");

        numTicketsTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numTicketsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTicketsTextFieldActionPerformed(evt);
            }
        });
        numTicketsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numTicketsTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(totalPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(buyTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numTicketsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(youthCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(adultCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(elderCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youthCheckBox)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adultCheckBox)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elderCheckBox)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTicketsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean getYouthSelected(){
        return youthCheckBox.isSelected();
    }
    public boolean getAdultSelected(){
        return adultCheckBox.isSelected();
    }
    
    public boolean getElderSelected(){
        return elderCheckBox.isSelected();
    }
    
    public String getCategoryComboBox(){
        return (String)categoryComboBox.getSelectedItem();
    }
    
    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:    
        
        //declare an object buytick of the class BuyTicketGUI
        BuyTicketGUI buytick = new BuyTicketGUI();  
        
        //check if the user selet the age
        if (buttonGroup1.isSelected(null)){            
            JOptionPane.showMessageDialog(null, "Please select your age!!");
        }
        
        //check if the user enterd the number of tickets
        else if (numTicketsTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your mumber of tickets!!");
        }
        
        //check if the user calculate the total cost
        else if(totalCostLabel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please press button Total Price to calculate your price first!!");
        }        
        
        else{            
            //transfer data to from a GUI frame to the another GUI frame
            BuyTicketGUI.categoryLabel.setText(this.categoryComboBox.getSelectedItem().toString());           
            BuyTicketGUI.ageLabel.setText(this.youthCheckBox.getText());
            BuyTicketGUI.ticketPriceLabel.setText(this.checkPriceLabel.getText());
            BuyTicketGUI.numTicketsLabel.setText(this.numTicketsTextField.getText());
            BuyTicketGUI.totalPriceLabel.setText(this.totalCostLabel.getText());            
            buytick.setVisible(true);
            buytick.pack();
            buytick.setLocationRelativeTo(null);
            buytick.setDefaultCloseOperation(EXIT_ON_CLOSE);
            this.dispose();
        }          
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    private void youthCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youthCheckBoxMouseClicked
        // TODO add your handling code here:  
        
        //declare an object temp and convet it to string
        String temp = (String)categoryComboBox.getSelectedItem();         
        checkPriceLabel.setVisible(true);          
        
        //ckect the prices for Youth
        if(temp.equals("Star")){
            p=new Youth();                
            ((Youth)(p)).computeStarYouthPrice();  
            double starYouthPrice=((Youth)(p)).getStarYouthPrice();                
            checkPriceLabel.setText(""+starYouthPrice);
        }
        
        if(temp.equals("Premium")){
            p=new Youth();
            ((Youth)(p)).computePremiumYouthPrice();  
            double premiumYouthPrice=((Youth)(p)).getPremiumYouthPrice();                
            checkPriceLabel.setText(""+premiumYouthPrice);                
        }
        
        if(temp.equals("Economy")){
            p=new Youth();
            ((Youth)(p)).computeEconomyYouthPrice();  
            double economyYouthPrice=((Youth)(p)).getEconomyYouthPrice();                
            checkPriceLabel.setText(""+economyYouthPrice);                  
        }        
    }//GEN-LAST:event_youthCheckBoxMouseClicked

    private void adultCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adultCheckBoxMouseClicked
        // TODO add your handling code here:
        
        //declare an object temp and convet it to string
        String temp = (String)categoryComboBox.getSelectedItem();         
        checkPriceLabel.setVisible(true);   
        
        //check the prices for Adult
        if(temp.equals("Star")){             
            p=new Adult();
            ((Adult)(p)).computeStarAdultPrice();  
            double starAdultPrice=((Adult)(p)).getStarAdultPrice();                
            checkPriceLabel.setText(""+starAdultPrice);          
        }   
            
        if(temp.equals("Premium")){
            p=new Adult();
            ((Adult)(p)).computePremiumAdultPrice();  
            double premiumAdultPrice=((Adult)(p)).getPremiumAdultPrice();                
            checkPriceLabel.setText(""+premiumAdultPrice);                
        }
            
        if(temp.equals("Economy")){
            p=new Adult();
            ((Adult)(p)).computeEconomyAdultPrice();  
            double economyAdultPrice=((Adult)(p)).getEconomyAdultPrice();                
            checkPriceLabel.setText(""+economyAdultPrice);                  
        }       
    }//GEN-LAST:event_adultCheckBoxMouseClicked

    private void totalPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceButtonActionPerformed
        // TODO add your handling code here:           
        
        //check if the text field is empty
        if(numTicketsTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the number of tickets!"); 
            numTicketsTextField.requestFocus();            
        }
        
        //ckeck if the user enter the number of tickets as 0
        else if (Integer.parseInt(numTicketsTextField.getText())<=0){
            JOptionPane.showMessageDialog(null, "You entered a wrong number of tickets, The number of tickets can not be 0!!");
            numTicketsTextField.requestFocus();
        }     
        else{    
            
            //calculate the total cost for Youth
            if(youthCheckBox.isSelected()){
                int numberTickets = Integer.parseInt(numTicketsTextField.getText());
                ((Youth)(p)).setNumberTickets(numberTickets);                
                ((Youth)(p)).computeTotalCost();
                double totalCost=((Youth)(p)).getTotalCost();
                totalCostLabel.setText("" +totalCost);
            }    
            
            //calculate the total cost for Adult
            else if(adultCheckBox.isSelected()){
                int numberTickets = Integer.parseInt(numTicketsTextField.getText());
                ((Adult)(p)).setNumberTickets(numberTickets);
                ((Adult)(p)).computeTotalCost();
                double totalCost=((Adult)(p)).getTotalCost();
                totalCostLabel.setText("" +totalCost);
            }
            
            //calculate the total cost for Elder
            else if(elderCheckBox.isSelected()){
                int numberTickets = Integer.parseInt(numTicketsTextField.getText());
                ((Elder)(p)).setNumberTickets(numberTickets);
                ((Elder)(p)).computeTotalCost();
                double totalCost=((Elder)(p)).getTotalCost();
                totalCostLabel.setText("" +totalCost);
            }            
            else{                
                JOptionPane.showMessageDialog(null, "Please select your age");                
            }                      
        }             
    }//GEN-LAST:event_totalPriceButtonActionPerformed
  
    private void elderCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderCheckBoxMouseClicked
        // TODO add your handling code here:
        
        //declare an object temp and convet it to string
        String temp = (String)categoryComboBox.getSelectedItem();         
        checkPriceLabel.setVisible(true);   
        
        //check the prices for Elder
        if(temp.equals("Star")){             
            p=new Elder();
            ((Elder)(p)).computeStarElderPrice();  
            double starElderPrice=((Elder)(p)).getStarElderPrice();                
            checkPriceLabel.setText(""+starElderPrice);          
        }   
            
        if(temp.equals("Premium")){
            p=new Elder();
            ((Elder)(p)).computePremiumElderPrice();  
            double premiumElderPrice=((Elder)(p)).getPremiumElderPrice();                
            checkPriceLabel.setText(""+premiumElderPrice);                
        }
            
        if(temp.equals("Economy")){
            p=new Elder();
            ((Elder)(p)).computeEconomyElderPrice();  
            double economyElderPrice=((Elder)(p)).getEconomyElderPrice();                
            checkPriceLabel.setText(""+economyElderPrice);                  
        } 
    }//GEN-LAST:event_elderCheckBoxMouseClicked

    private void categoryComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryComboBoxMouseClicked
        // TODO add your handling code here:  
        
        //clear the buttonGroup
        buttonGroup1.clearSelection();           
    }//GEN-LAST:event_categoryComboBoxMouseClicked

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
        
        //clear the buttonGroup
        buttonGroup1.clearSelection();             
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void numTicketsTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTicketsTextFieldKeyPressed
        // TODO add your handling code here:
        
        //check if the user enterd  numbers only
        int key = evt.getKeyCode();
            if((key>=KeyEvent.VK_0 && key<=KeyEvent.VK_9)||(key>=KeyEvent.VK_NUMPAD0&&key<=KeyEvent.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE){
                //numTicketsTextField.setEditable(true);
                //numTicketsTextField.setBackground(Color.white);
            }
            else{
                
                //show message box                 
                numTicketsTextField.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Enter numbers only, letters or any special characters are not allowed"); 
                numTicketsTextField.setEditable(true);
                numTicketsTextField.setBackground(Color.white);
                numTicketsTextField.setText("");
                numTicketsTextField.requestFocus();
            }
    }//GEN-LAST:event_numTicketsTextFieldKeyPressed

    private void numTicketsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTicketsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTicketsTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckPriceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckPriceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckPriceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckPriceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckPriceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adultCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel checkPriceLabel;
    private javax.swing.JCheckBox elderCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numTicketsTextField;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JButton totalPriceButton;
    private javax.swing.JCheckBox youthCheckBox;
    // End of variables declaration//GEN-END:variables
}
